In [ ]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6],[6,7,8],[8,9,10]]])
print(a) # Вывод самого массива
print(a.ndim) # Измерение массива
print(a.shape) # Состав массива , 1 - 3-х мерный , 4 строки , 3 столбца
print(a.size) # Кол-во элементов массива
print(a.itemsize) # Кол-во памяти  1 элемента массива
print(a.nbytes) # Кол-во памяти занимаемое всем массивом
#print(a[1, 3, 1]) # Узнаём что стоит на этом месте в массиве ( 1 строка , 3 место) P.S. НУМЕРАЦИЯ С НУЛЯ
#print(a[1, :]) # Выводит все элементы 2 строки

b = np.zeros((2, 2)) # Создаёт массив заполненный нулями , ones , full , random.randint , identity
print(b)


[[[ 1  2  3]
  [ 4  5  6]
  [ 6  7  8]
  [ 8  9 10]]]
3
(1, 4, 3)
12
8
96
[[0. 0.]
 [0. 0.]]


In [ ]:
print("1) массив чисел от 0 до 9:")
arr = np.arange(10)
arr

1) массив чисел от 0 до 9:


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print("2) массив чисел(3х3), состоящий из единиц и f.ones:")
arr = np.ones((3, 3))
arr

2) массив чисел(3х3), состоящий из единиц и f.ones:


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
print("3) массив чисел(2х2), состоящий из рандомов:")
arr = np.random.randint(1, 11, size=(2, 2))
arr

3) массив чисел(2х2), состоящий из рандомов:


array([[2, 8],
       [3, 7]])

In [ ]:
arr = np.random.rand(5, 5)
print("4.1) массив 5х5")
arr

4.1) массив 5х5


array([[0.36105303, 0.54988184, 0.18036337, 0.48207177, 0.55269674],
       [0.36287569, 0.42656328, 0.83016338, 0.5901125 , 0.02885123],
       [0.9241658 , 0.65524723, 0.5926214 , 0.86532127, 0.28332884],
       [0.78046217, 0.21145293, 0.12064148, 0.60942917, 0.84513397],
       [0.54059671, 0.66797033, 0.86679605, 0.56089243, 0.15447479]])

In [ ]:
print("4.2) массив 5х5 со средним значением:")
srednee = np.mean(arr)
srednee # Output медианы

4.2) массив 5х5 со средним значением:


0.5217266953649607

In [ ]:
print("5) массив 5х5 с рандомным заполнением от 0 до 1:")
arr = np.random.rand(5, 5)
print("Сам массив: " , arr)
col_sums = arr.sum(axis=0)
print("Суммы столбцов = " , col_sums)

5) массив 5х5 с рандомным заполнением от 0 до 1:
Сам массив:  [[0.70817352 0.18697365 0.93062002 0.67805318 0.9478522 ]
 [0.53279352 0.41633856 0.349431   0.3619995  0.69013832]
 [0.59489118 0.06294912 0.35474874 0.96703374 0.23956475]
 [0.88064878 0.22902641 0.88513118 0.02839961 0.27381393]
 [0.62327031 0.18782636 0.44012128 0.26076855 0.31495263]]
Сумма столбцов =  [3.33977731 1.0831141  2.96005221 2.29625457 2.46632183]
